# Form implementation generated from reading ui file 'E:\TTU 2\Resource\UI Design\Log_Aktivitas.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(907, 632)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Help_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Help_Button.setGeometry(QtCore.QRect(820, 0, 75, 23))
        self.Help_Button.setObjectName("Help_Button")
        self.Admin_Page_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Admin_Page_Button.setGeometry(QtCore.QRect(820, 20, 75, 23))
        self.Admin_Page_Button.setObjectName("Admin_Page_Button")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 811, 31))
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"text-decoration: underline;\n"
"font: 75 16pt \"Times New Roman\";\n"
"text-decoration: underline;")
        self.label_7.setObjectName("label_7")
        self.Tabel_Log_Aktivitas = QtWidgets.QTableView(parent=self.centralwidget)
        self.Tabel_Log_Aktivitas.setGeometry(QtCore.QRect(10, 50, 891, 561))
        self.Tabel_Log_Aktivitas.setObjectName("Tabel_Log_Aktivitas")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Help_Button.setText(_translate("MainWindow", "Help"))
        self.Admin_Page_Button.setText(_translate("MainWindow", "Admin Page"))
        self.label_7.setText(_translate("MainWindow", "Katalog Digital Ruang Arsip Kantor Dinas Kependudukan dan Pencatatan Sipil Kota Salatiga"))
